IF OBJECT_ID(N'[Food].[Meals]', N'U') IS NULL
BEGIN
	CREATE TABLE [Food].[Meals]
	(
		[MealId] [int] IDENTITY(1,1) NOT NULL,
		[Name] [nvarchar](200) NOT NULL,
		[Category] [nvarchar](20) NOT NULL,
		CONSTRAINT [PK__Food__Meals] PRIMARY KEY CLUSTERED 
	(
		[MealId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
